services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=catalog'
      - 'POSTGRES_USER=catalog'
    ports:
      - '5433:5432'
    volumes:
      - catalog_pgdata:/var/lib/postgresql/data

volumes:
  catalog_pgdata:
